version: "3"
tasks:
  format:
    desc: Format Terraform code files
    cmd: terraform fmt -recursive .

  build-go-image:
    desc: Build go image for DB stopper function
    dir: "db-shutdown"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    cmds:
      - go build -o ./bin/bootstrap
      - cd ./bin && zip bootstrap.zip bootstrap

  init-group:
    desc: Initialize a resource group template with terraform
    sources:
      - "main.tf"
    requires:
      vars:
        - "GROUP"
        - "PROVIDER"
    dir: "{{.PROVIDER}}/{{.GROUP}}/template"
    cmd: terraform init -backend-config=../values/backend.config

  validate-group:
    desc: Validate a resource group template with terraform
    sources:
      - "*.tf"
    requires:
      vars:
        - "GROUP"
        - "PROVIDER"
    dir: "{{.PROVIDER}}/{{.GROUP}}/template"
    cmds:
      - task: init-group
        vars:
          PROVIDER: "{{.PROVIDER}}"
          GROUP: "{{.GROUP}}"
      - terraform validate

  deploy-group:
    desc: Deploy a specific resource group with Terraform
    deps:
      - "build-go-image"
    requires:
      vars:
        - "GROUP"
    dir: '{{.PROVIDER | default "aws"}}/{{.GROUP}}/template'
    cmds:
      - task: validate-group
        vars:
          PROVIDER: "{{.PROVIDER}}"
          GROUP: "{{.GROUP}}"

      - terraform apply -auto-approve -input=false -var-file=../values/terraform.tfvars

  remove-group:
    desc: Delete a specific resource group with Terraform
    deps:
      - "build-go-image"
    requires:
      vars:
        - "GROUP"
    dir: '{{.PROVIDER | default "aws"}}/{{.GROUP}}/template'
    cmds:
      - task: validate-group
        vars:
          PROVIDER: "{{.PROVIDER}}"
          GROUP: "{{.GROUP}}"

      - terraform destroy -auto-approve -input=false -var-file=../values/terraform.tfvars

  kubeconfig-aws:
    desc: Update kubeconfig from an AWS EKS cluster
    dir: "aws/cluster/template"
    cmd: |
      aws eks update-kubeconfig \
              --name $(terraform output -raw cluster_name) \
              --region $(terraform output -raw region)

